package prograsof.cinemagenta.vistas;

import prograsof.cinemagenta.interfaces.RefreshListener;
import prograsof.cinemagenta.modelos.*;

import javax.swing.*;
import java.awt.*;

public class AgregarPeliculaPanel extends JPanel {

    private final Cartelera cartelera = new Cartelera();
    private final RefreshListener listener; 

    // Componentes del formulario
    private JTextField tituloField = new JTextField(20);
    private JTextField directorField = new JTextField(20);
    private JTextField anioField = new JTextField(10);
    private JTextField duracionField = new JTextField(10);
    private JComboBox<String> generoComboBox; // Cambiado a JComboBox
    private JButton guardarButton = new JButton("Guardar Película");

    public AgregarPeliculaPanel(RefreshListener listener) {
        this.listener = listener;
        
        // Inicializar el JComboBox con los géneros
        String[] generos = {"Comedia", "Drama", "Accion", "Ciencia ficcion", "Terror", "Animacion", "Aventura", "Musical"};
        generoComboBox = new JComboBox<>(generos);

        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5); 
        gbc.anchor = GridBagConstraints.WEST;

        // Añadir etiquetas y campos de texto
        gbc.gridx = 0; gbc.gridy = 0; add(new JLabel("Título:"), gbc);
        gbc.gridx = 1; add(tituloField, gbc);

        gbc.gridx = 0; gbc.gridy = 1; add(new JLabel("Director:"), gbc);
        gbc.gridx = 1; add(directorField, gbc);

        gbc.gridx = 0; gbc.gridy = 2; add(new JLabel("Año:"), gbc);
        gbc.gridx = 1; add(anioField, gbc);

        gbc.gridx = 0; gbc.gridy = 3; add(new JLabel("Duración (min):"), gbc);
        gbc.gridx = 1; add(duracionField, gbc);

        gbc.gridx = 0; gbc.gridy = 4; add(new JLabel("Género:"), gbc);
        gbc.gridx = 1; add(generoComboBox, gbc); // Usamos JComboBox en lugar de JTextField

        // Añadir el botón
        gbc.gridx = 0; gbc.gridy = 5; gbc.gridwidth = 2; gbc.anchor = GridBagConstraints.CENTER;
        add(guardarButton, gbc);

        // Añadir el escuchador de eventos al botón
        guardarButton.addActionListener(e -> guardarPelicula());
    }
    
    private void guardarPelicula() {
        try {
            // 1. Obtener los datos del formulario
            String titulo = tituloField.getText();
            String director = directorField.getText();
            int anio = Integer.parseInt(anioField.getText());
            int duracion = Integer.parseInt(duracionField.getText());
            String genero = (String) generoComboBox.getSelectedItem(); // Obtenemos el valor del JComboBox

            // 2. Crear un objeto Pelicula
            Pelicula nuevaPelicula = new Pelicula(0, titulo, director, anio, duracion, genero);

            // 3. Llamar al controlador para guardar en la DB
            cartelera.crearPelicula(nuevaPelicula);
            
            // 4. Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(this, "Película guardada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            
            // 5. Llamar al método de refresco y limpiar los campos
            if (listener != null) {
                listener.onRefreshNeeded();
            }
            tituloField.setText("");
            directorField.setText("");
            anioField.setText("");
            duracionField.setText("");
            generoComboBox.setSelectedIndex(0);
            
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El año y la duración deben ser números válidos.", "Error de entrada", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
