package prograsof.cinemagenta.vistas;

import prograsof.cinemagenta.interfaces.RefreshListener;
import prograsof.cinemagenta.modelos.*;

import javax.swing.*;
import java.awt.*;

public class EliminarPeliculaPanel extends JPanel {

    private final Cartelera cartelera = new Cartelera();
    private final RefreshListener listener;
    
    private JTextField idField = new JTextField(5);
    private JButton eliminarButton = new JButton("Eliminar Película");
    private JButton limpiarButton = new JButton("Limpiar ID");

    public EliminarPeliculaPanel(RefreshListener listener) {
        this.listener = listener;
        
        setLayout(new GridBagLayout());
        GridBagConstraints gbc = new GridBagConstraints();
        gbc.insets = new Insets(5, 5, 5, 5);
        gbc.anchor = GridBagConstraints.CENTER;

        gbc.gridx = 0; gbc.gridy = 0;
        add(new JLabel("ID de la película a eliminar:"), gbc);
        gbc.gridx = 1;
        add(idField, gbc);

        gbc.gridx = 0; gbc.gridy = 1;
        gbc.gridwidth = 1;
        add(eliminarButton, gbc);
        gbc.gridx = 1;
        add(limpiarButton, gbc);

        eliminarButton.addActionListener(e -> eliminarPelicula());
        limpiarButton.addActionListener(e -> limpiarCampos());
    }

    private void limpiarCampos() {
        idField.setText("");
    }

    private void eliminarPelicula() {
        try {
            int id = Integer.parseInt(idField.getText());

            // 1. Validar que la película exista
            Pelicula peliculaAEliminar = cartelera.obtenerPeliculaPorId(id);
            if (peliculaAEliminar == null) {
                JOptionPane.showMessageDialog(this, "❌ Película con ID " + id + " no existe. No se puede eliminar.", "Error de Existencia", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            // 2. Confirmar la eliminación
            int confirmacion = JOptionPane.showConfirmDialog(this,
                    "¿Seguro que quieres eliminar '" + peliculaAEliminar.getTitulo() + "' (ID: " + id + ")?", "Confirmar Eliminación",
                    JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);

            if (confirmacion == JOptionPane.YES_OPTION) {
                cartelera.eliminarPelicula(id);
                JOptionPane.showMessageDialog(this, "✅ Película eliminada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
                
                if (listener != null) {
                    listener.onRefreshNeeded();
                }
                limpiarCampos();
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "El ID debe ser un número válido.", "Error de Entrada", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
