package prograsof.cinemagenta.vistas;

import prograsof.cinemagenta.interfaces.RefreshListener;
import prograsof.cinemagenta.modelos.*;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.awt.*;
import java.util.List;

public class VerCarteleraPanel extends JPanel {

    private final Cartelera cartelera = new Cartelera();
    private JTable tablaPeliculas;
    private DefaultTableModel tablaModelo;

    public VerCarteleraPanel() {
        setLayout(new BorderLayout());

        // Definir las columnas de la tabla
        String[] columnas = {"ID", "Título", "Director", "Año", "Duración", "Género"};
        tablaModelo = new DefaultTableModel(columnas, 0);
        tablaPeliculas = new JTable(tablaModelo);
        
        // Hacer la tabla desplazable
        JScrollPane scrollPane = new JScrollPane(tablaPeliculas);
        add(scrollPane, BorderLayout.CENTER);
    }

    // Método público para cargar los datos en la tabla
    public void cargarDatosTabla() {
        // Limpiar la tabla antes de cargar nuevos datos para evitar duplicados
        tablaModelo.setRowCount(0);
        
        List<Pelicula> peliculas = cartelera.obtenerPeliculas();
        
        for (Pelicula p : peliculas) {
            Object[] fila = {
                p.getId(),
                p.getTitulo(),
                p.getDirector(),
                p.getAnio(),
                p.getDuracion(),
                p.getGenero()
            };
            tablaModelo.addRow(fila);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
