package prograsof.cinemagenta;

import prograsof.cinemagenta.interfaces.RefreshListener;
import prograsof.cinemagenta.vistas.*;

import javax.swing.*;
import java.awt.*;


public class Menu extends javax.swing.JFrame implements RefreshListener{

    private CardLayout cardLayout = new CardLayout();
    private JPanel mainPanel = new JPanel();
    private VerCarteleraPanel verCarteleraPanel;
    private JComboBox<String> cbGenero;       
    private JCheckBox chkDesde, chkHasta;     
    private JSpinner spDesde, spHasta;
    
    public Menu() {
        setTitle("Magenta - Gestión de Cartelera");
        setSize(800, 600);
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);

        mainPanel.setLayout(cardLayout);
        
        // Creamos una instancia de cada panel
        this.verCarteleraPanel = new VerCarteleraPanel();
        AgregarPeliculaPanel agregarPeliculaPanel = new AgregarPeliculaPanel(this);
        ActualizarPeliculaPanel actualizarPeliculaPanel = new ActualizarPeliculaPanel(this);
        EliminarPeliculaPanel eliminarPeliculaPanel = new EliminarPeliculaPanel(this);
        BuscarPeliculaPanel buscarPeliculaPanel = new BuscarPeliculaPanel(); 
        

        // Añadimos las vistas/formularios al panel principal
        mainPanel.add(verCarteleraPanel, "VER");
        mainPanel.add(agregarPeliculaPanel, "AGREGAR");
        mainPanel.add(actualizarPeliculaPanel, "ACTUALIZAR");
        mainPanel.add(eliminarPeliculaPanel, "ELIMINAR");
        mainPanel.add(buscarPeliculaPanel, "BUSCAR");

        // Creamos y configuramos la barra de herramientas y los botones
        JToolBar toolBar = new JToolBar();
        toolBar.setFloatable(false);
        JButton btnVer = new JButton("Listar Peliculas");
        JButton btnAgregar = new JButton("Agregar Película");
        JButton btnActualizar = new JButton("Actualizar Película");
        JButton btnEliminar = new JButton("Eliminar Película");
        JButton btnBuscar = new JButton("Buscar Película");
        
        toolBar.add(btnVer);
        toolBar.add(btnAgregar);
        toolBar.add(btnActualizar);
        toolBar.add(btnEliminar);
        toolBar.add(btnBuscar);
        
        // El ActionListener del botón "Ver" llama al método de refresco
        btnVer.addActionListener(e -> {
            cardLayout.show(mainPanel, "VER");
            verCarteleraPanel.cargarDatosTabla(); // Refrescamos la tabla cada vez que se muestra
        });
        btnAgregar.addActionListener(e -> cardLayout.show(mainPanel, "AGREGAR"));
        btnActualizar.addActionListener(e -> cardLayout.show(mainPanel, "ACTUALIZAR"));
        btnEliminar.addActionListener(e -> cardLayout.show(mainPanel, "ELIMINAR"));
        btnBuscar.addActionListener(e -> cardLayout.show(mainPanel, "BUSCAR"));

        add(toolBar, BorderLayout.NORTH);
        add(mainPanel, BorderLayout.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // </editor-fold>
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1019, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 559, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    
    @Override
    public void onRefreshNeeded() {
        verCarteleraPanel.cargarDatosTabla();
    }
    
    public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> {
            Menu frame = new Menu();
            frame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
